namespace Funi;

public sealed class Fun
{
    static readonly ImmutableList<string> CBTitems = ImmutableList.Create(
        "Afar",
        "Abkhazian",
        "Afrikaans",
        "Amharic",
        "Arabic",
        "Arabic (U.A.E.)",
        "Arabic (Bahrain)",
        "Arabic (Algeria)",
        "Arabic (Egypt)",
        "Arabic (Iraq)",
        "Arabic (Jordan)",
        "Arabic (Kuwait)",
        "Arabic (Lebanon)",
        "Arabic (libya)",
        "Arabic (Morocco)",
        "Arabic (Oman)",
        "Arabic (Qatar)",
        "Arabic (Saudi Arabia)",
        "Arabic (Syria)",
        "Arabic (Tunisia)",
        "Arabic (Yemen)",
        "Assamese",
        "Aymara",
        "Azeri",
        "Bashkir",
        "Belarusian",
        "Bulgarian",
        "Bihari",
        "Bislama",
        "Bengali",
        "Tibetan",
        "Breton",
        "Catalan",
        "Corsican",
        "Czech",
        "Welsh",
        "Danish",
        "German",
        "German (Austria)",
        "German (Switzerland)",
        "German (Liechtenstein)",
        "German (Luxembourg)",
        "Divehi",
        "Bhutani",
        "Greek",
        "English",
        "English (Australia)",
        "English (Belize)",
        "English (Canada)",
        "English (United Kingdom)",
        "English (Ireland)",
        "English (Jamaica)",
        "English (New Zealand)",
        "English (Philippines)",
        "English (Trinidad)",
        "English (United States)",
        "English (South Africa)",
        "English (Zimbabwe)",
        "Esperanto",
        "Spanish",
        "Spanish (Argentina)",
        "Spanish (Bolivia)",
        "Spanish (Chile)",
        "Spanish (Colombia)",
        "Spanish (Costa Rica)",
        "Spanish (Dominican Republic)",
        "Spanish (Ecuador)",
        "Spanish (España)",
        "Spanish (Guatemala)",
        "Spanish (Honduras)",
        "Spanish (Mexico)",
        "Spanish (Nicaragua)",
        "Spanish (Panama)",
        "Spanish (Peru)",
        "Spanish (Puerto Rico)",
        "Spanish (Paraguay)",
        "Spanish (El Salvador)",
        "Spanish (United States)",
        "Spanish (Uruguay)",
        "Spanish (Venezuela)",
        "Estonian",
        "Basque",
        "Farsi",
        "Finnish",
        "Fiji",
        "Faeroese",
        "French",
        "French (Belgium)",
        "French (Canada)",
        "French (Switzerland)",
        "French (Luxembourg)",
        "French (Monaco)",
        "Frisian",
        "Irish",
        "Gaelic",
        "Galician",
        "Guarani",
        "Gujarati",
        "Hausa",
        "Hebrew",
        "Hindi",
        "Croatian",
        "Hungarian",
        "Armenian",
        "Interlingua",
        "Indonesian",
        "Interlingue",
        "Inupiak",
        "Indonesian",
        "Icelandic",
        "Italian",
        "Italian (Switzerland)",
        "Hebrew",
        "Japanese",
        "Yiddish",
        "Javanese",
        "Georgian",
        "Kazakh",
        "Greenlandic",
        "Cambodian",
        "Kannada",
        "Korean",
        "Konkani",
        "Kashmiri",
        "Kurdish",
        "Kirghiz",
        "Kyrgyz",
        "Latin",
        "Lingala",
        "Laothian",
        "Slovenian",
        "Lithuanian",
        "Latvian",
        "Malagasy",
        "Maori",
        "FYRO Macedonian",
        "Malayalam",
        "Mongolian",
        "Moldavian",
        "Marathi",
        "Malay",
        "Maltese",
        "Burmese",
        "Nauru",
        "Norwegian (Bokmal)",
        "Nepali (India)",
        "Dutch",
        "Dutch (Belgium)",
        "Norwegian",
        "Norwegian (Bokmal)",
        "Occitan",
        "(Afan)/Oromoor/Oriya",
        "Oriya",
        "Punjabi",
        "Polish",
        "Pashto/Pushto",
        "Portuguese",
        "Portuguese (Brazil)",
        "Quechua",
        "Rhaeto,Romanic",
        "Kirundi",
        "Romanian",
        "Romanian (Moldova)",
        "Russian",
        "Russian (Moldova)",
        "Kinyarwanda",
        "Sanskrit",
        "Sorbian",
        "Sindhi",
        "Sangro",
        "Serbo,Croatian",
        "Singhalese",
        "Slovak",
        "Slovenian",
        "Samoan",
        "Shona",
        "Somali",
        "Albanian",
        "Serbian",
        "Siswati",
        "Sesotho",
        "Sundanese",
        "Swedish",
        "Swedish (Finland)",
        "Swahili",
        "Sutu",
        "Syriac",
        "Tamil",
        "Telugu",
        "Tajik",
        "Thai",
        "Tigrinya",
        "Turkmen",
        "Tagalog",
        "Tswana",
        "Tonga",
        "Turkish",
        "Tsonga",
        "Tatar",
        "Twi",
        "Ukrainian",
        "Urdu",
        "English",
        "Uzbek",
        "Vietnamese",
        "Volapuk",
        "Wolof",
        "Xhosa",
        "Yiddish",
        "Yoruba",
        "Chinese",
        "Chinese (China)",
        "Chinese (Hong Kong SAR)",
        "Chinese (Macau SAR)",
        "Chinese (Singapore)",
        "Chinese (Taiwan)",
        "Zulu"
    );

    public Fun(HoyoLauncher.HoyoLauncherSettings.HoyoSettings window)
    {
        foreach(var item in CBTitems.ToImmutableArray())
            window.Funni.Items.Add(item);
    }
}