//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LaunchText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LaunchText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoyoLauncher.Properties.LaunchText", typeof(LaunchText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Play.
        /// </summary>
        public static string GAME_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("GAME_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string GAME_DOWNLOAD {
            get {
                return ResourceManager.GetString("GAME_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string GAME_EXTRACT_TEXT {
            get {
                return ResourceManager.GetString("GAME_EXTRACT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is Running.
        /// </summary>
        public static string GAME_LAUNCHED_TEXT {
            get {
                return ResourceManager.GetString("GAME_LAUNCHED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play on Mobile.
        /// </summary>
        public static string GAME_MOBILE {
            get {
                return ResourceManager.GetString("GAME_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO INTERNET.
        /// </summary>
        public static string GAME_NO_INTERNET_TEXT {
            get {
                return ResourceManager.GetString("GAME_NO_INTERNET_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not set.
        /// </summary>
        public static string GAME_NOTFOUND {
            get {
                return ResourceManager.GetString("GAME_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string GAME_SOON_TEXT {
            get {
                return ResourceManager.GetString("GAME_SOON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string GAME_UPDATE_TEXT {
            get {
                return ResourceManager.GetString("GAME_UPDATE_TEXT", resourceCulture);
            }
        }
    }
}
