//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoyoLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In Rewards.
        /// </summary>
        public static string CHECKIN_TIP {
            get {
                return ResourceManager.GetString("CHECKIN_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Play.
        /// </summary>
        public static string GAME_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("GAME_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is Running.
        /// </summary>
        public static string GAME_LAUNCHED_TEXT {
            get {
                return ResourceManager.GetString("GAME_LAUNCHED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not set.
        /// </summary>
        public static string GAME_NOTFOUND {
            get {
                return ResourceManager.GetString("GAME_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string GAME_SOON_TEXT {
            get {
                return ResourceManager.GetString("GAME_SOON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string GAME_UPDATE_TEXT {
            get {
                return ResourceManager.GetString("GAME_UPDATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenshinImpact.exe.
        /// </summary>
        public static string GENSHIN_IMPACT_EXEC {
            get {
                return ResourceManager.GetString("GENSHIN_IMPACT_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Genshin Impact Launcher.
        /// </summary>
        public static string GENSHIN_IMPACT_TIP {
            get {
                return ResourceManager.GetString("GENSHIN_IMPACT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin Impact.
        /// </summary>
        public static string GENSHIN_IMPACT_TITLE {
            get {
                return ResourceManager.GetString("GENSHIN_IMPACT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Hompage.
        /// </summary>
        public static string HOMEPAGE_TIP {
            get {
                return ResourceManager.GetString("HOMEPAGE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH3.exe.
        /// </summary>
        public static string HONKAI_IMPACT_THIRD_EXEC {
            get {
                return ResourceManager.GetString("HONKAI_IMPACT_THIRD_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Honkai Impact 3rd Launcher.
        /// </summary>
        public static string HONKAI_IMPACT_THIRD_TIP {
            get {
                return ResourceManager.GetString("HONKAI_IMPACT_THIRD_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honkai Impact 3rd.
        /// </summary>
        public static string HONKAI_IMPACT_THIRD_TITLE {
            get {
                return ResourceManager.GetString("HONKAI_IMPACT_THIRD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarRail.exe.
        /// </summary>
        public static string HONKAI_STAR_RAIL_EXEC {
            get {
                return ResourceManager.GetString("HONKAI_STAR_RAIL_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Honkai: Star Rail Launcher.
        /// </summary>
        public static string HONKAI_STAR_RAIL_TIP {
            get {
                return ResourceManager.GetString("HONKAI_STAR_RAIL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honkai Star Rail.
        /// </summary>
        public static string HONKAI_STAR_RAIL_TITLE {
            get {
                return ResourceManager.GetString("HONKAI_STAR_RAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Tears of Themis on Mobile.
        /// </summary>
        public static string TOT_TIP {
            get {
                return ResourceManager.GetString("TOT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Zenless Zone Zero Launcher.
        /// </summary>
        public static string ZZZ_TIP {
            get {
                return ResourceManager.GetString("ZZZ_TIP", resourceCulture);
            }
        }
    }
}
