//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sdk-os-static.mihoyo.com/bh3_global/mdk/launcher/api/resource?launcher_id" +
            "=10")]
        public string HI3_VERSION_API {
            get {
                return ((string)(this["HI3_VERSION_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sdk-os-static.mihoyo.com/hk4e_global/mdk/launcher/api/resource?launcher_i" +
            "d=10&key=gcStgarh")]
        public string GENSHIN_VERSION_API {
            get {
                return ((string)(this["GENSHIN_VERSION_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resourc" +
            "e?launcher_id=35&key=vplOVX8Vn7cwG8yb")]
        public string HSR_VERSION_API {
            get {
                return ((string)(this["HSR_VERSION_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sdk-os-static.mihoyo.com/bh3_global/mdk/launcher/api/content?filter_adv=t" +
            "rue&language=en-us&launcher_id=10")]
        public string HI3_CONTENT_API {
            get {
                return ((string)(this["HI3_CONTENT_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sdk-os-static.mihoyo.com/hk4e_global/mdk/launcher/api/content?filter_adv=" +
            "true&language=en-us&launcher_id=10&key=gcStgarh")]
        public string GENSHIN_CONTENT_API {
            get {
                return ((string)(this["GENSHIN_CONTENT_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/content" +
            "?filter_adv=true&language=en-us&launcher_id=35&key=vplOVX8Vn7cwG8yb")]
        public string HSR_CONTENT_API {
            get {
                return ((string)(this["HSR_CONTENT_API"]));
            }
        }
    }
}
