//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoyoLauncher.Properties.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin Impact Check-In Rewards.
        /// </summary>
        public static string GENSHIN_IMPACT_TIP {
            get {
                return ResourceManager.GetString("GENSHIN_IMPACT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Hompage.
        /// </summary>
        public static string HOMEPAGE_TIP {
            get {
                return ResourceManager.GetString("HOMEPAGE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honkai Impact 3rd Check-In Rewards.
        /// </summary>
        public static string HONKAI_IMPACT_THIRD_TIP {
            get {
                return ResourceManager.GetString("HONKAI_IMPACT_THIRD_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honkai: Star Rail Check-In Rewards.
        /// </summary>
        public static string HONKAI_STAR_RAIL_TIP {
            get {
                return ResourceManager.GetString("HONKAI_STAR_RAIL_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Original Launcher.
        /// </summary>
        public static string LAUNCHER_TIP {
            get {
                return ResourceManager.GetString("LAUNCHER_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Interactive Map.
        /// </summary>
        public static string MAPPAGE_TIP {
            get {
                return ResourceManager.GetString("MAPPAGE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Screenshot folder.
        /// </summary>
        public static string SCREENSHOT_TIP {
            get {
                return ResourceManager.GetString("SCREENSHOT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Menu.
        /// </summary>
        public static string TOPBUTTON_HOME_TIP {
            get {
                return ResourceManager.GetString("TOPBUTTON_HOME_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Cached Data / Check Latest Version.
        /// </summary>
        public static string TOPBUTTON_REFRESH_TIP {
            get {
                return ResourceManager.GetString("TOPBUTTON_REFRESH_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string TOPBUTTON_SETTINGS_TIP {
            get {
                return ResourceManager.GetString("TOPBUTTON_SETTINGS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tears of Themis Check-In Rewards.
        /// </summary>
        public static string TOT_TIP {
            get {
                return ResourceManager.GetString("TOT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zenless Zone Zero Check-In Rewards.
        /// </summary>
        public static string ZZZ_TIP {
            get {
                return ResourceManager.GetString("ZZZ_TIP", resourceCulture);
            }
        }
    }
}
